INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic "Dumitru Mangeron" Bacău', 5.06);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Naţional "Vasile Alecsandri" Bacău', 8.962);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic "Grigore Antipa" Bacău', 5.584);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Teoretic "Henri Coandă" Bacău', 6.314);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic "Petru Rareş" Bacău', 3.316);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic "Anghel Saligny" Bacău', 4.986);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Naţional Pedagogic "Ştefan Cel Mare" Bacău', 8.374);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Economic "Ion Ghica" Bacău', 6.35);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Cu Program Sportiv Bacău', 4.71);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Tehnic De Comunicaţii "N.Vasilescu-Karpen" Bacău', 7.69);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Naţional "Gheorghe Vrănceanu" Bacău', 9.428);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul "Mihai Eminescu" Bacău', 8.366);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Naţional Catolic "Sf.Iosif" Bacău', 7.894);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Naţional "Ferdinand I" Bacău', 9.18);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Naţional De Artă "George Apostu" Bacău', 7);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic "Alexandru Vlahuţă" Podu Turcului', 5.814);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic Dărmăneşti', 6.076);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Teoretic "Ion Borcea" Buhuşi', 7.008);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Naţional "Grigore Moisil" Oneşti', 8.428);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Naţional "Dimitrie Cantemir" Oneşti', 8.91);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Cu Program Sportiv "Nadia Comăneci" Oneşti', 5.396);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic "Petru Poni" Oneşti', 5.53);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Teologic "Fericitul Ieremia" Oneşti', 6.27);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Tehnic "Gheorghe Asachi" Oneşti', 6.448);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic Oneşti', 4.866);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic "Jacques M. Elias" Sascut', 5.186);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Tehnic "Grigore Cobălcescu" Moineşti', 5.614);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Teoretic "Spiru Haret" Moineşti', 7.932);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Naţional "Costache Negri" Târgu Ocna', 7.008);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic Târgu Ocna', 4.378);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic Răchitoasa', 4.042);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic "Georgeta J.Cancicov" Parincea', 3.558);
INSERT INTO medieadmitere (hs, medie) VALUES ('Colegiul Tehnic "Dimitrie Ghika" Comăneşti', 6.826);
INSERT INTO medieadmitere (hs, medie) VALUES ('Liceul Tehnologic Făget', 5.15);